import type { Config } from "@eslint/config-helpers";

export default {
	name: "General rules",
	rules: {
		"array-callback-return": "warn",
		"arrow-body-style": "warn",
		"block-scoped-var": "warn",
		"complexity": "warn",
		"curly": ["warn", "multi-line", "consistent"],
		"default-case": "warn",
		"default-case-last": "warn",
		"default-param-last": "warn",
		"dot-notation": "warn",
		"func-name-matching": "warn",
		"grouped-accessor-pairs": "warn",
		"id-denylist": "warn",
		"id-match": "warn",
		"max-classes-per-file": "warn",
		"max-depth": "warn",
		"max-lines": ["warn", { skipBlankLines: true, skipComments: true }],
		"max-lines-per-function": ["warn", { skipComments: true }],
		"max-nested-callbacks": "warn",
		"max-params": ["warn", 6],
		"new-cap": "warn",
		"no-alert": "warn",
		"no-array-constructor": "warn",
		"no-await-in-loop": "warn",
		"no-caller": "warn",
		"no-cond-assign": "off",
		"no-constant-binary-expression": "off",
		"no-constant-condition": ["warn", { checkLoops: false }],
		"no-constructor-return": "warn",
		"no-debugger": "off",
		"no-div-regex": "warn",
		"no-duplicate-imports": "warn",
		"no-empty": ["warn", { allowEmptyCatch: true }],
		"no-empty-function": "warn",
		"no-eval": "warn",
		"no-extend-native": "warn",
		"no-extra-bind": "warn",
		"no-extra-label": "warn",
		"no-implicit-coercion": "warn",
		"no-implied-eval": "warn",
		"no-invalid-this": "error",
		"no-iterator": "warn",
		"no-label-var": "warn",
		"no-labels": "error",
		"no-lone-blocks": "warn",
		"no-loop-func": "warn",
		"no-loss-of-precision": "off",
		"no-multi-str": "error",
		"no-nested-ternary": "warn",
		"no-new-func": "warn",
		"no-new-wrappers": "warn",
		"no-object-constructor": "warn",
		"no-octal-escape": "warn",
		"no-proto": "warn",
		"no-restricted-exports": "warn",
		"no-restricted-globals": "warn",
		"no-restricted-imports": "warn",
		"no-restricted-properties": "warn",
		"no-restricted-syntax": "warn",
		"no-script-url": "warn",
		"no-self-compare": "warn",
		"no-sequences": "warn",
		"no-shadow": "warn",
		"no-template-curly-in-string": "warn",
		"no-throw-literal": "warn",
		"no-undef-init": "warn",
		"no-unmodified-loop-condition": "warn",
		"no-unneeded-ternary": "warn",
		"no-unreachable-loop": "warn",
		"no-unused-expressions": "warn",
		"no-useless-call": "warn",
		"no-useless-computed-key": "warn",
		"no-useless-concat": "warn",
		"no-useless-rename": "warn",
		"no-useless-return": "warn",
		"no-var": "warn",
		"no-void": "warn",
		"object-shorthand": "warn",
		"operator-assignment": "warn",
		"prefer-arrow-callback": "warn",
		"prefer-const": "warn",
		"prefer-exponentiation-operator": "warn",
		"prefer-numeric-literals": "warn",
		"prefer-regex-literals": "warn",
		"prefer-rest-params": "warn",
		"require-atomic-updates": "warn",
		"require-await": "warn",
		"sort-imports": ["warn", { allowSeparatedGroups: true }],
		"symbol-description": "warn",
		"unicode-bom": "warn",
		"vars-on-top": "warn",
		"yoda": ["warn", "never", { onlyEquality: true }],
	},
} as Config;
